<a href="https://colab.research.google.com/github/irfanizzath/MLPractice/blob/main/Lasso_and_Ridge_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**L1 Regularization** - Lasso regression <br>
**L2 Regularization** - Ridge regression

In [146]:
import pandas as pd
import matplotlib.pyplot as pl
import numpy as np
import seaborn as sns
from matplotlib import rcParams

In [155]:
df = pd.read_csv('/content/50_Startups.csv')
df.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [148]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [149]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [156]:
df.State = le.fit_transform(df.State)

In [151]:
df

R&D Spend  Administration  Marketing Spend  State     Profit
0    165349.20       136897.80        471784.10      2  192261.83
1    162597.70       151377.59        443898.53      0  191792.06
2    153441.51       101145.55        407934.54      1  191050.39
3    144372.41       118671.85        383199.62      2  182901.99
4    142107.34        91391.77        366168.42      1  166187.94
..         ...             ...              ...    ...        ...
103  119943.24       156547.42        256512.92      1  132602.65
104  114523.61       122616.84        261776.23      2  129917.04
105   78013.11       121597.55        264346.06      0  126992.93
106   94657.16       145077.58        282574.31      2  125370.37
107   91749.16       114175.79        294919.57      1  124266.90

[108 rows x 5 columns]

### **X and Y Split**

In [157]:
Y = df['Profit']
X = df.drop(columns = ['Profit'],axis =1)

In [158]:
X

R&D Spend  Administration  Marketing Spend  State
0    165349.20       136897.80        471784.10      2
1    162597.70       151377.59        443898.53      0
2    153441.51       101145.55        407934.54      1
3    144372.41       118671.85        383199.62      2
4    142107.34        91391.77        366168.42      1
..         ...             ...              ...    ...
103  119943.24       156547.42        256512.92      1
104  114523.61       122616.84        261776.23      2
105   78013.11       121597.55        264346.06      0
106   94657.16       145077.58        282574.31      2
107   91749.16       114175.79        294919.57      1

[108 rows x 4 columns]

### **Normalization**

In [159]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_scaled = pd.DataFrame(scaler.fit_transform(X), columns = X.columns)

### **Train Test Split**

In [175]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state = 0)

In [176]:
X_train.shape

(86, 4)

In [177]:
X_test.shape

(22, 4)

In [178]:
from sklearn.linear_model import Lasso ,  Ridge

In [179]:
l = Lasso()
r = Ridge()

In [180]:
l.fit(X_train,Y_train)

Lasso()

In [181]:
r.fit(X_train,Y_train)

Ridge()

In [182]:
pred_r =r.predict(X_test)
pred_r

array([ 54556.32416702, 130017.92166782,  84687.15947095, 173295.2223158 ,
       108917.94957822, 128735.89224253, 128736.35934265, 155951.19177423,
       117814.48562718,  52712.59507338, 102790.3781561 , 119096.2726001 ,
        54556.32416702, 124206.72612243,  88379.01243395, 126261.35613731,
       126261.35613731,  98802.1865801 ,  74278.88209886, 141546.67661999,
       145564.21281487, 150251.73759042])

In [183]:
pred_r_train = r.predict(X_train)
pred_r_train

array([109172.11701154, 162907.31389068, 100464.139996  , 167970.8492119 ,
       122667.96190528,  49887.13653097,  96390.68310219, 143886.79143792,
        85348.38393902, 188005.75965694, 183451.16760721, 157862.5695242 ,
       127596.0763847 , 118725.97104944, 122667.96190528, 128736.35934265,
       119096.2726001 , 127596.0763847 , 108917.94957822,  93971.40528091,
        65903.04456747, 183451.16760721,  81352.03770302,  75188.38192378,
        79135.42233855, 162907.31389068, 141546.67661999, 132321.48447687,
        81352.03770302,  75752.10844107, 157862.5695242 , 145564.21281487,
       130017.92166782, 132321.48447687, 188005.75965694,  97035.56715902,
       104697.62664321, 117814.48562718, 128735.89224253, 128735.89224253,
       114288.26358192,  93907.91802285, 114288.26358192,  98727.48396016,
       150251.73759042, 128736.35934265,  68760.8213074 , 167970.8492119 ,
        93971.40528091, 173295.2223158 , 145564.21281487,  78309.20334753,
       107823.62811616, 1

In [184]:
pred_l =l.predict(X_test)
pred_l

array([ 48384.86814735, 134845.52354938,  76486.64641608, 181551.13594979,
       112961.07382208, 134236.64101991, 129218.98004997, 160017.16104325,
       116754.23112994,  46273.04713164, 102272.49339834, 115567.13437352,
        48384.86814735, 119116.48630482,  88593.22703248, 127104.80005829,
       127104.80005829,  90948.41312188,  58678.78647171, 146299.80323437,
       149413.8490298 , 152502.10158276])

In [185]:
pred_l_train = l.predict(X_train)
pred_l_train

array([110345.06847036, 171315.14087949,  98167.3495588 , 173976.20312604,
       116391.72815898,  48721.24977913,  98703.60466908, 155799.50522602,
        83170.9100649 , 193321.34343103, 188881.62393281, 163693.83927011,
       129123.17340829, 116686.52466738, 116391.72815898, 129218.98004997,
       115567.13437352, 129123.17340829, 112961.07382208,  97485.61160597,
        60875.10406774, 188881.62393281,  75063.94710207,  70422.60445166,
        75022.69207191, 171315.14087949, 146299.80323437, 131295.79320222,
        75063.94710207,  70551.48514181, 163693.83927011, 149413.8490298 ,
       134845.52354938, 131295.79320222, 193321.34343103,  89804.0356455 ,
       102129.68691995, 116754.23112994, 134236.64101991, 134236.64101991,
       110753.19950999,  91202.84834487, 110753.19950999,  98111.94129321,
       152502.10158276, 129218.98004997,  64563.00320539, 173976.20312604,
        97485.61160597, 181551.13594979, 149413.8490298 ,  71073.04408273,
       114694.60730979, 1

In [186]:
profit =pd.DataFrame({'Actual_Profit':Y_test, 'Ridge_pred':pred_r,'Lasso_pred':pred_l})
profit.head(10)

Actual_Profit     Ridge_pred     Lasso_pred
84        64926.08   54556.324167   48384.868147
10       146121.95  130017.921668  134845.523549
75        90708.19   84687.159471   76486.646416
2        191050.39  173295.222316  181551.135950
24       108552.04  108917.949578  112961.073822
100      144259.40  128735.892243  134236.641020
107      124266.90  128736.359343  129218.980050
7        155752.60  155951.191774  160017.161043
16       126992.93  117814.485627  116754.231130
86        42559.73   52712.595073   46273.047132

In [187]:
from sklearn import metrics

In [188]:
print('R2_Score')
print(f'Lasso : {metrics.r2_score(Y_test, pred_l)}')
print(f'Ridge : {metrics.r2_score(Y_test, pred_r)}')

R2_Score
Lasso : 0.9259035724996549
Ridge : 0.9095565216441847


In [189]:
print('RMSE')
print(f'Lasso : {np.sqrt(metrics.mean_squared_error(Y_test, pred_l))}')
print(f'Ridge : {np.sqrt(metrics.mean_squared_error(Y_test, pred_r))}')

# Lesser RMSE is more better

RMSE
Lasso : 9798.251585438255
Ridge : 10825.266082933194
